### PR TITLE
Protoscript

### PR DESCRIPTION
**Pull request by noahseger**
## Results

| Implementation                          | JavaScript         | TypeScript         | Standard<br>Plugin | Required tests                        | Recommended tests                        |
|-----------------------------------------|:------------------:|:------------------:|:------------------:|:-------------------------------------:|:----------------------------------------:|
| [Protobuf-ES](impl/protobuf-es)         | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | <sub></sub><br><sup>(0&nbsp;failures)<sub>     | <sub></sub><br><sup>(1&nbsp;failures)<sub>     |
| [protobuf-ts](impl/protobuf-ts)         | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | <sub></sub><br><sup>(6&nbsp;failures)<sub>     | <sub></sub><br><sup>(5&nbsp;failures)<sub>     |
| [protoscript](impl/protoscript)         | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | <sub></sub><br><sup>(934&nbsp;failures)<sub>    | <sub></sub><br><sup>(487&nbsp;failures)<sub>    |
| [google-protobuf](impl/google-protobuf) | :heavy_check_mark: | :x:                | :heavy_check_mark: | <sub></sub><br><sup>(387&nbsp;failures)<sub> | <sub></sub><br><sup>(216&nbsp;failures)<sub> |
| [protobuf.js](impl/protobuf.js)         | :heavy_check_mark: | :heavy_check_mark: | :x:                | <sub></sub><br><sup>(928&nbsp;failures)<sub>     | <sub></sub><br><sup>(471&nbsp;failures)<sub>     |
| [protoc-gen-ts](impl/protoc-gen-ts)     | :x:                | :heavy_check_mark: | :heavy_check_mark: | <sub></sub><br><sup>(1085&nbsp;failures)<sub>    | <sub></sub><br><sup>(369&nbsp;failures)<sub>    |
| [ts-proto](impl/ts-proto)               | :x:                | :heavy_check_mark: | :heavy_check_mark: | <sub></sub><br><sup>(848&nbsp;failures)<sub>        | <sub></sub><br><sup>(528&nbsp;failures)<sub>

### CODE REVIEW

**Comment by noahseger** [comment]
@smaye81 it's actually needed for both, AFAIK. I have zero depth around understanding the nature of the remaining PB2/PB3 failures, so there could still be some errors in the way I structured the `protoscript` runner.

Mostly my goal here is to start a conversation around whether https://github.com/tatethurston/TwirpScript might be interested in moving to the `protobuf-es` runtime, or if that project wants to trade off the smaller runtime for more compliance (I think it's about 1/2 the size of `protobuf-es` today?).

Tangent: I ran into that `tsx` log output error and spent soooo much time figuring out why the test runner was hanging before I read the `ts-proto` README and realized you went through the same thing 🤦 This whole approach is really great, love the project and thanks for setting it up!

**Comment by smaye81** [comment]
I played around with this last night just to see why it fails and you are correct that it's needed for both `proto2` and `proto3`. The `proto2` failures are because of the usage of `groups`, which is what I suspected. However, `proto3` fails because of the usage of double underscores (i.e. `__`) in field names. 

I don't think we want to patch the code to execute the tests because that presents false results since we are modifying the actual code to get the suite to run. However, I do hear you re: starting a conversation around TwirpScript and it is much appreciated to see if they'd be interested in using Protobuf-ES. Perhaps this PR is enough of a conversation starter, though? Maybe Tate Thurston would be amenable to upstreaming your changes into ProtoScript so that we can officially add it to the conformance tests?

And yeah the hanging test runner thing was a nightmare haha! Sorry you had to put up with that also. I spent an inordinate amount of time debugging that. Appreciate the kind words!

**Comment by noahseger** [comment]
> However, proto3 fails because of the usage of double underscores (i.e. __) in field names.

Does this affect only the JSON test cases?

In any case, yes agree we should remove the patch before considering this reviewable — I'll work to upstream the changes.

**Comment by smaye81** [comment]
I actually didn't test which tests passed if those were removed, so I'm not entirely sure. At any rate, I appreciate you working to upstream the changes. Let me know if I can help.

**Comment by noahseger** [comment]
@smaye81 many hours later... Protoscript 0.15 was released with improvements to my vendored changes, so this should pass "clean" now.

**Review by smaye81 — APPROVED** [review]

**Pull request merged**
